services:
  mc:
    build:
      context: .
      dockerfile: Dockerfile
    image: multiegg_compose:compose
    command: /bin/bash /app/install.sh
    develop:
      watch:
        - action: rebuild
          path: ./scripts